- directions.go
- directions_test.go
- encoding.go
- examples/directions/cmdline/main.go
- types.go
> Adding traffic predictions to Directions API

- places.go
- places_test.go
PTAL @samthor 
Fixes https://github.com/googlemaps/google-maps-services-go/issues/57
> Adding permanently closed to PlacesSearchResult.

- directions_test.go
@domesticmouse 
Note for future: `reflect.DeepEquals` will fail on `nil` slices vs empty slices, but they're both printed as `[]`.
> add test for Directions with DateTime

- client.go
> Fix for https://github.com/googlemaps/google-maps-services-go/issues/64

- .travis.yml
- README.md
> Marking Golang 1.5 as minimum required version

- geocoding.go
- The link to the component filtering documentation was wrong.
> Fix documentation URL

- directions.go
- distancematrix.go
- distancematrix_test.go
Fixing https://github.com/googlemaps/google-maps-services-go/issues/78
> Making avoid work for DistanceMatrix

- examples/places/placeautocomplete/placeautocomplete.go
- places.go
- places_test.go
- types.go
CLA submission has been down, I'm waiting my validation.
As commented in #84 
PlaceType* are apparently code generated, so AutocompletePlaceType should maybe too but I didn't find how too. I would be glad to do it if you show me the way.
An I'm opened to any remark or suggestion, just let me know if I need to correct some stuff.
> Fix Place Autcomplete Type

- CONTRIBUTORS
- places.go
I was looking for this data point and realized it was missing!
> added adr microformat to PlaceDetailsResult

- places.go
> Adding omitempty on PlaceSearchResult

- client.go
- geolocation.go
- geolocation_test.go
See issue #97
- Added Client.post and Client.postJSON methods to support the API
- Added geolocation module & types
- Added a couple of local tests for Geolocation API response parsing
Not sure if any other tests would be useful?
> Added geolocation API

- client.go
Brett -- Here is a proposed change to address #98. In addition to the unit tests, we've used it in our application for geocode and directions API requests.
> Makes client-level rate-limiting optional

- places.go
- places_test.go
This adds support for the Places Autocomplete `structured_formatting` fields.
> add StructuredFormatting field to AutocompletePrediction

- staticmap.go
Add this service https://developers.google.com/maps/documentation/static-maps/intro
> add Static Map service

- client.go
- distancematrix_test.go
- elevation_test.go
- geocoding.go
- geocoding_test.go
- geolocation_test.go
- roads_test.go
- staticmap.go
[all]: simplificated code by gofmt -s
> [staticmap]: enabled client ID auth; [geocoding]: disabled client ID auth

- geolocation_test.go
- timezone_test.go
> Remove pretty dep from tests

- roads.go
- roads_test.go
This PR adds the Nearest Roads API - https://developers.google.com/maps/documentation/roads/nearest
As described in the contribution guidelines, the CLA was signed beforehand
> Add Nearest Roads API

- examples/places/nearbysearch/nearbysearch.go
Remove extraneous duplicate word.
> Fix small typo - correct pagetoken flag description

- client.go
Fix for https://github.com/googlemaps/google-maps-services-go/issues/125
PTAL @broady
> Converting to golang.org/x/time/rate

- examples/places/nearbysearch/nearbysearch.go
Small change which adds the correct flag description to the `NearbySearch` example.
> Fixing incorrect flag description.

- distancematrix.go
> Wrap distance matrix comments to make them better fit godoc.

- client.go
- directions.go
- directions_test.go
- distancematrix.go
- elevation.go
- examples/elevation/cmdline/main.go
- geocoding.go
- geolocation.go
- places.go
- polyline.go
- polyline_test.go
- roads.go
- staticmap.go
- timezone.go
- transport.go
- types.go
Fix for https://github.com/googlemaps/google-maps-services-go/issues/143
> Documentation formatting.

- .travis.yml
- directions.go
- directions_test.go
Fix #138 
- ~using `strings.Builder` only support 1.10 +~
Please review my code
Best,
Alpha
> FIX: optimze waypoint issue #138

- distancematrix_test.go
- examples/distancematrix/cmdline/main.go
Additional code for testing https://github.com/googlemaps/google-maps-services-go/issues/159
> Adding TrafficModel to examples, and an extra test

- staticmap.go
- staticmap_test.go
Whilst using this library I had a requirement to support Map Styles, specifically to disable POI in my Google Static Map.
This PR contains Map Style support for all supported Map Styles in the Google Static Maps API.
> MapStyles support

- directions.go
- directions_test.go
New field added to the google directions api. It has helpful information (ex. about train number).
> add field TripShortName

- .gitignore
- types.go
> refactor(google-maps-services-go): removed deprecated place types

- types.go
This provides support for `geometry/location` and similar subfields. closes #202
> support subfields in places field masks

- client.go
- client_test.go
> feat: support experience id header

- go.mod
- go.sum
> build: use go mod

- .github/workflows/release.yml
- .releaserc
Automate releases with semantic-release!
> build: support semantic relase

- places.go
- places_test.go
- types.go
Add support for business_status.
> feat: support business_status

- encoding.go
- encoding_test.go
Thank you for opening a Pull Request!
---
Fixes #229 🦕
> Instantiate duration encoder for EncDurationInTraffic field

- places.go
- places_test.go
> fix: mutation original request issue #208

- types.go
Thank you for opening a Pull Request!
---
Fixes #<issue_number_goes_here> 🦕
> fix: add place type of supermarket

- places.go
- places_test.go
- types.go
> #201 feat: remove old fields

- .github/workflows/release.yml
- .github/workflows/test.yml
- places.go
- places_test.go
- types.go
Add support for new place details fields described in https://cloud.google.com/blog/products/maps-platform/help-users-discover-more-new-places-api-updates
> feat: add new place details fields

- places.go
- places_test.go
This fixes parsing of secondary opening hours. 
Fixes #281 🦕
> fix: secondary opening hours parsing

- types.go
Thank you for opening a Pull Request!
---
- [ X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X ] Ensure the tests and linter pass
- [ X] Code coverage does not decrease (if any source code was changed)
Fixes #284
> fix: business_status placessearchfieldmask

- README.md
Add the following new badges to `README.md`:
[![Go Report Card](https://goreportcard.com/badge/github.com/googlemaps/google-maps-services-go)](https://goreportcard.com/report/github.com/googlemaps/google-maps-services-go)
[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)
> chore: Add status badges to READM

- examples/staticmap/cmdline/main.go
- staticmap.go
Add support for map_id parameter to static map request and static map cli app
---
Fixes #269  🦕
> feat: add map_id parameter to static map request

- types.go
Thank you for opening a Pull Request!
---
Fixes #<issue_number_goes_here> 🦕
I didnt open an issue this feels pretty straight forward but i can open one if you want. Drugstore doesnt follow the other store in that its not separated but drugstore is the correct type according to the website.
https://developers.google.com/maps/documentation/places/web-service/supported_types
> added missing placetypes
