googlemaps/google-maps-services-go

places.go, places_test.go
PTAL @samthor 
Fixes https://github.com/googlemaps/google-maps-services-go/issues/56
=> 	Adding page token to TextSearch request

internal/types.go
Per: https://developers.google.com/maps/documentation/directions/intro#TransitDetails
Time values are in seconds, not milliseconds.
=> Correct erroneous time.Time values returned by the library.

distancematrix.go, distancematrix_test.go
Added traffic models to Distance Matrix API. Pretty simple change. Note this is already present in Directions API so this keeps the two in line.
=> Adding traffic model to Distance Matrix

distancematrix.go, distancematrix_test.go, encoding.go
In current distancematrix response struct, there is no duration_in_traffic var, which exists in raw json responses from google api when the "departure_time" param is provided. 
So, add it into the struct.
=> add duration_in_traffic in distancematrix response

geocoding.go, geocoding_test.go
The Geocoding API allows reverse geocoding using either a lat-long combination, or a place_id.
The Go libraries did not support the place_id usecase, which is why I have added the PlaceID property to the GeocodingRequest struct.
Have also added a ReverseGeocode() method. This is because the Geocode() method checks if LatLng and Address and Components are nil, which can be the case for a reverse geocoding request, which only requires either a LatLng, or a PlaceID.
Added a test function for this. And also modified another test which checks the same reverse geocoding functionality.
Reverse Geocoding API required parameters => https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding
=> Added PlaceID to GeocodingRequest, and a ReverseGeocode() function

directions.go, directions_test.go
Note, this changes the API for fares, such that we can now detect if fares were omitted in the response.
For #72
=> Adding test coverage for Fares.

geocoding.go, geocoding_test.go
Geocoding requires an ongoing support for short lived custom parameters,
as evidenced by the `new_forward_geocoder` parameter documented in
https://googlegeodevelopers.blogspot.com.au/2016/11/address-geocoding-in-google-maps-apis.html
PTAL @samthor
=> Adding custom parameter support

polyline.go, polyline_test.go
Fixes issue #86
- Add test to detect bug in polyline decoding
- Fix decodeInt polyline decoding  
Byte cannot be negative. raw=63 should create b=-1 but since b is
byte b become 0. Fixed by only using 5 bits of b and initiating result from 0
=> Fix #86 polyline decoding

geocoding.go, geocoding_test.go
As documented here:
https://developers.google.com/maps/documentation/geocoding/intro#GeocodingResponses
The Geometry may contain an attribute called bounds and this attribute
is not on AddressGeometry, This PR fixes it. Issue #93
=> Include Bounds on Geocodin Response

latlng.go
fmt.Sprintf with %g will encode floats using the scientific notation (%e) instead of decimal point notation (%f) if the exponent is large enough. In practice, latitudes/longitudes <=0.0001 will be converted with %e, while the Google Maps APIs don't support this notation. This can be prevented by always converting those latlng using %f.
The default decimal precision of %f is 6. This should be enough for API queries (about 111.32 mm at equator, https://en.wikipedia.org/wiki/Decimal_degrees).
=> Use %f instead of %g in LatLng.String()

client.go, client_test.go
Google Maps API allow developers to include a client query
parameter that may be used to (for example) better control
the usage of the rate limits and calls to api (as a form of
identification)
Other libraries such as Python Library already allow developers
to set this parameter (https://github.com/googlemaps/google-maps-services-python/blob/master/googlemaps/client.py#L67)
The google developer documentation also describe this parameter:
https://developers.google.com/maps/documentation/geocoding/get-api-key
under the section 'Choosing an authentication method for your application'
->Authentication using a client ID and digital signature
=> Include Channel Parameter on Client URL

README.md, examples/staticmap/cmdline/main.go, latlng_test.go, staticmap.go, staticmap_test.go
Also, in passing, updated the StaticMap implementation to return a decoded image, instead of the raw HTTP Response. Felt more appropriate.
=> Tests for StaticMap, LatLng. Clean up markdown warnings in README.md.

.travis.yml, examples/staticmap/cmdline/main.go, staticmap.go
I think the GAE/Go SDK still uses Go 1.6 mainly
=> Fix build failure with Go 1.6

places.go, places_test.go
Add struct tag to `Predictions` property in `AutocompleteResponse` to keep the json key in lower case when we marshal the struct to json.
=> add struct tag to AutocompleteResponse predictions

geocoding.go
A fix for a problem pointed out by @jqin
=> Adding back clientID to geocoding

geocoding.go, geocoding_test.go
PR for #115 
When Geocoding response have status ZERO_RESULTS - it is considered as not an error, but just results with zero len.
=> geocoding ZERO_RESULTS response status not an error

staticmap.go
The static maps was not working when using coordinates instead of location name for the Center point.
I removed the url.QueryEscape for the r.Center which fixes this issue.
=> Fix for the Center point to work with coordinates

examples/geocoding/cmdline/main.go, geocoding.go, geocoding_test.go
Google maps API has  field "partial_math" in results, and it's helpfull for cases when we need to know if result is not exact
https://developers.google.com/maps/documentation/geocoding/intro#Results
And for plus_code https://developers.google.com/maps/documentation/geocoding/intro#pluscode
In this case it's reasonable to add such fields in GeocodingResult
=> Added `partial_match` and `plus_code` to GeocodingResult

geocoding.go
This makes the error handing in ReverseGeocode consistent with Geocode.
Updates issue #135.
=> Improve ReverseGeocode error handling

README.md, examples/staticmap/cmdline/main.go, staticmap.go, staticmap_test.go
Hi!
Recently created design for Maps Static API integration works wrong. 
Problems:
1. Static map styles have [priorities](https://developers.google.com/maps/documentation/maps-static/styling#style-syntax). 
> Style rules are applied in the order that you specify. Do not combine multiple operations into a single style operation. Instead, define each operation as a separate entry in the style array.
>
> Note: Order is important, as some operations are not commutative. Features and/or elements that are modified through style operations (usually) already have existing styles. The operations act on those existing styles, if present.
But Golang maps do not guarantee a sequence. Hence the following style defined as a map works ambiguously:
```
all:
geometry:
color: "0xe8eff2"
water:
geometry: …
```
=> a new contract for map styles

places.go, places_test.go
Hi there!
This PR makes `sessiontoken` optional in AutoComplete request according to the [doc]( https://developers.google.com/places/web-service/autocomplete#session_tokens)
[Doc](https://developers.google.com/places/web-service/autocomplete#place_autocomplete_requests) says: 
```
Optional parameters:
sessiontoken — A random string which identifies...
...
If the sessiontoken parameter is omitted, each request is billed independently. 
```
@domesticmouse @broady check it please as soon as possible!
Thank you!
=> make sessiontoken optional in autocomplete

client.go, directions_test.go, geocoding.go, geocoding_test.go, places_test.go, timezone_test.go
This is meant as a first step to streamline error handling (see #135).
Instead of peppering the code with ZERO_RESULTS checks (680e071a043395a60a4e03ca3ab6ee011650a5fb and 57ebecb10c25dc67331ccc5a7b40a3fc0bd5ff0a), I think that StatusError() should simply not return an error when the status is ZERO_RESULTS.
This is actually in line with the [Python client](https://github.com/googlemaps/google-maps-services-python/blob/master/googlemaps/client.py#L284).
=> Do not return an error in StatusError() when the status is ZERO_RESULTS

staticmap.go, staticmap_test.go
The Marker's custom icon parameter has a scale descriptor that is undocumented. Found it here: https://stackoverflow.com/questions/10336646/how-can-i-use-high-resolution-custom-markers-with-the-scale-parameter-in-google
For example:
http://maps.googleapis.com/maps/api/staticmap?&size=600x400&scale=2&style=visibility:on%20&style=feature:water%7Celement:geometry%7Cvisibility:on%20&style=feature:landscape%7Celement:geometry%7Cvisibility:on%20&markers=scale:2%7Canchor:32,10%7Cicon:https://goo.gl/5y3S82%7CCanberra+ACT%20&markers=anchor:topleft%7Cicon:http://tinyurl.com/jrhlvu6%7CMelbourne+VIC%20&markers=anchor:topright%7Cicon:https://goo.gl/1oTJ9Y%7CSydney+NSW&key={YOUR_API_KEY}
Compare the **star** (scale=2) marker with the other two (no scale value, i.e. scale=1).
=> Add missing Marker scale parameter for static maps

places.go, places_test.go
As stated in the [doc](https://developers.google.com/places/web-service/search#TextSearchRequests), there is a region parameter which found in google-maps-services-python and google-maps-services-java but not in this repo.
=> Add missing Region field for TextSearchRequest

staticmap.go
Hi,
In our company we have the use case to generate polylines with a significant number of Points.
As the current library does not use the Encode method, the url generated is too long.
This Pull Request permits to set an option to true (`UsePolylineEncoding`), to activate the Encoding option.
Regards
=> Convert Path.Location to an encoded polyline string

staticmap.go, staticmap_test.go
I have a need to position a Marker using a postal address rather than the long,lat location.
The Google Static Maps API supports this, just this package was lacking the support.
Thanks for your time.
=> Google Static Maps API: Added support for Marker using location address

client.go, directions.go, distancematrix.go, elevation.go, examples/staticmap/cmdline/main.go, geocoding.go, geolocation.go, internal/signer.go, places.go, roads.go, staticmap.go, timezone.go
Per [FAQ](https://developers.google.com/maps/faq#digsig):
> For a limited number of daily requests to the Maps Static and Street View Static APIs, the digital signature is optional. With that being said, we strongly recommend that you use both an API key and a digital signature to authenticate your requests, regardless of your usage.
=> Add support for signing Static Maps API requests

places.go
Add request exceeds error for PlacePhoto API.
Because not handling request exceeds error.
- Documents
https://developers.google.com/places/web-service/photos#place_photo_requests
=> Add request exceeds error for PlacePhoto API.

places.go, types.go
There is a field called `user_ratings_total` that is missing from this Go API bindings implementation
Here you can find it on this page: 
https://developers.google.com/places/web-service/details#fields
You can also see this field in the test data https://github.com/googlemaps/google-maps-services-go/blob/master/places_test.go#L672
This PR is intended to add this missing field
=> Places API: add missing user_ratings_total

places.go, places_test.go
Notes:
1) `orign` and `distance_meters` are described here: https://developers.google.com/places/web-service/autocomplete
2) I selected to unmarshal `distance_meters` into an int because I have never seen it return a float and googlemaps seems to use int for distances. However, I do not know if this is accurate - I could not find documentation and the other googlemaps libraries seem to also lack support for `origin` and `distance_meters`
3) I didn't see a place to squeeze in a test for `distance_meters` so I didn't add one. Afaik it would simply be an unmarshaling test anyways
=> Add origin and distance_meters support for Places AutoComplete

README.md, client.go, metrics/metric.go, metrics/metric_test.go, metrics/opencensus.go, metrics/opencensus_test.go
By default it will use a no-op logger, an opencensus logger is also provided.
Fixes #237 🦕
=> feat: Add metrics instrumentation using OpenCensus. (#237)

client.go, client_test.go
In scenario when singleton SDK client used to make calls for different customers, setting the [experienceId](https://developers.google.com/maps/documentation/one_per_ride/managing-trips#go_example_2) explicitly for every new call leads to the race conditions between the different requests.
I propose this PR to add ability passing the experienceId using context.
=> feat: add ability to pass the experience id within the context

client.go
Fixes #250 🦕
Mirrors error handling approach from `getJSON` / `postJSON` in `getBinary`.
=> fix: handles case where binary request does not return a response

places.go
This adds the `Language` field to `FindPlaceFromTextRequest`.  For more information, see:
https://developers.google.com/maps/documentation/places/web-service/search
=> fix: Add Language to FindPlaceFromTextRequest

README.md
Removed empty spaces in the go get command.
Fixes #277 🦕
=> chore: Removed empty spaces in the README for the go get command

.github/workflows/test.yml, README.md
- Add link to new client librarires
- Remove old references to client ID
- Move to standard Terms and Support language
=> docs: update README.md

places.go, places_test.go
Added RelativeTimeDescription to PlaceReview struct
Added property to TestPlaceDetails unit test > successfully passed
Fixes #271  🦕
=> feat: add relative_time_description property to PlaceReview
